import Link from "next/link";
import { CTA, Counties, ContactForm, ServiceCards } from "@/components/Sections";
import { companyDescription, site } from "@/lib/site";

export default function Home() {
  return <main>
    <section className="hero-grid px-4 py-20 text-white md:py-28"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><p className="mb-4 inline-flex rounded-full bg-white/15 px-4 py-2 text-sm font-bold">Serving Broward, Palm Beach & Miami-Dade Counties</p><h1 className="display text-5xl font-black leading-tight md:text-7xl">HVAC & Appliance Repair Services Across South Florida</h1><p className="mt-6 max-w-2xl text-lg text-blue-100">Service HQ Inc. provides professional air conditioning, heating, and appliance repair services with honesty, integrity, and over 10 years of hands-on experience.</p><div className="mt-8 flex flex-wrap gap-3"><a className="btn-primary" href={site.phoneHref}>Call {site.phone}</a><Link className="btn-secondary" href="/contact">Request Service</Link></div></div><div className="glass rounded-[2rem] p-6"><div className="service-pattern h-96 rounded-[1.5rem]"></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm font-bold"><div className="rounded-2xl bg-white/15 p-4">10+ Years Experience</div><div className="rounded-2xl bg-white/15 p-4">Locally Owned</div><div className="rounded-2xl bg-white/15 p-4">Honest Service</div><div className="rounded-2xl bg-white/15 p-4">South Florida</div></div></div></div></section>
    <section className="px-4 py-16"><div className="mx-auto max-w-7xl"><h2 className="display text-4xl font-black text-navy">Services</h2><p className="mt-3 max-w-2xl text-slate-600">Focused repair services for comfort, performance, and everyday convenience.</p><div className="mt-8"><ServiceCards /></div></div></section>
    <section className="bg-soft px-4 py-16"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><h2 className="display text-4xl font-black text-navy">Experience You Can Trust</h2><p className="mt-5 text-lg leading-8 text-slate-700">{companyDescription}</p><Link href="/about" className="btn-outline mt-7">About Service HQ</Link></div><div className="card"><h3 className="display text-2xl font-black text-navy">Why Homeowners Choose Service HQ</h3><ul className="mt-5 grid gap-4 text-slate-700"><li>✓ Locally owned and operated</li><li>✓ Over 10 years of hands-on experience</li><li>✓ Honest and reliable service</li><li>✓ Customized service for individual needs</li></ul></div></div></section>
    <section className="px-4 py-16"><div className="mx-auto max-w-7xl"><h2 className="display text-4xl font-black text-navy">Proudly Serving</h2><div className="mt-8"><Counties /></div></div></section>
    <section className="bg-soft px-4 py-16"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><h2 className="display text-4xl font-black text-navy">See What Customers Are Saying</h2><p className="mt-4 text-slate-600">Visit the Service HQ Google Reviews profile to read customer feedback.</p><a href={site.reviewUrl} className="btn-primary mt-6" target="_blank">View Google Reviews</a></div><ContactForm /></div></section>
    <CTA />
  </main>;
}
