import Link from "next/link";
import { site } from "@/lib/site";

export function CTA() { return <section className="bg-navy px-4 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><h2 className="display text-3xl font-black md:text-5xl">Need HVAC or appliance repair?</h2><p className="mt-3 text-blue-100">Contact Service HQ today for professional service across South Florida.</p></div><div className="flex flex-wrap gap-3"><a className="btn-primary" href={site.phoneHref}>Call {site.phone}</a><Link className="btn-secondary" href="/contact">Request Service</Link></div></div></section> }

export function ServiceCards() { return <div className="grid gap-6 md:grid-cols-3">{site.services.map((s) => <Link href={s.href} key={s.href} className="card group"><div className="mb-5 h-36 rounded-2xl service-pattern"></div><h3 className="display text-2xl font-black text-navy group-hover:text-serviceBlue">{s.title}</h3><p className="mt-3 text-slate-600">{s.description}</p><span className="mt-5 inline-block font-bold text-action">Learn more</span></Link>)}</div> }

export function Counties() { return <div className="grid gap-5 md:grid-cols-3">{site.counties.map((c) => <div key={c} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="display text-xl font-black text-navy">{c}</h3><p className="mt-2 text-slate-600">HVAC and appliance repair services.</p></div>)}</div> }

export function ContactForm() { return <form className="card grid gap-4"><div className="grid gap-4 md:grid-cols-2"><input className="rounded-2xl border border-slate-200 p-4" placeholder="Name"/><input className="rounded-2xl border border-slate-200 p-4" placeholder="Phone"/></div><input className="rounded-2xl border border-slate-200 p-4" placeholder="Email"/><textarea className="min-h-36 rounded-2xl border border-slate-200 p-4" placeholder="How can Service HQ help?"/><button className="btn-primary" type="button">Request Service</button><p className="text-xs text-slate-500">Form is ready for connection to your preferred email or CRM provider.</p></form> }
